# Pizza API

## To use these HTTP endpoint install the REST Client plugin in VSCode.

### Get all the Pizzas from the API

GET https://pizza-api.projectcodex.net/api/pizzas

### Create a cart

GET https://pizza-api.projectcodex.net/api/pizza-cart/create?username=sifiso


### Get a cart

GET https://pizza-api.projectcodex.net/api/pizza-cart/e4MnralryB/get

### Add a pizza to the cart

POST https://pizza-api.projectcodex.net/api/pizza-cart/add
content-type: application/json

{
	"cart_code" : "J7DS8Dqioo",
	"pizza_id" : 3
}

### Add a pizza to the cart

POST https://pizza-api.projectcodex.net/api/pizza-cart/add
content-type: application/json

{
	"cart_code" : "J7DS8Dqioo",
	"pizza_id" : 11
}

### Remove a pizza from the cart

POST https://pizza-api.projectcodex.net/api/pizza-cart/remove
content-type: application/json

{
	"cart_code" : "J7DS8Dqioo",
	"pizza_id" : 3
}

### GET all the carts for a given user

GET https://pizza-api.projectcodex.net/api/pizza-cart/username/sifiso

### GET all the active carts for a user

GET https://pizza-api.projectcodex.net/api/pizza-cart/username/sifiso/active


### Pay for a pizza from the cart

POST https://pizza-api.projectcodex.net/api/pizza-cart/pay	
content-type: application/json

{
	"cart_code" : "J7DS8Dqioo",
	"amount" : 200
}



### Get featured pizzas


GET https://pizza-api.projectcodex.net/api/pizzas/featured?username=sifiso


### SET featured pizzas

POST https://pizza-api.projectcodex.net/api/pizzas/featured
content-type: application/json

{
	"username" : "sifiso",
	"pizza_id" : 5
}